package basicClasses;

import java.io.Serializable;

public enum RequestType implements Serializable {
    ADD_ORDER,
    GET_MENU_ITEMS,
    GET_TABLE_ID,
    SEND_NOTIFICATION,
    CHEF_PASSWORD_CHECK,
    CHEF_APPROVED,
    CHEF_DISAPPROVED,
    NEW_ORDER,
    ADDED_TO_ORDER,
    ITEM_STATE_CHANGED,
    SEND_PARTIAL,
    ORDER_FINISHED,
    CHEF_REQUESTS_WAITER,
    CUSTOMER_REQUESTS_WAITER,
    WAITER_PASSWORD_CHECK,
    WAITER_APPROVED,
    WAITER_DISAPPROVED,
    FETCH_ORDERS;
}
